### ISSUE TITLE
The CSS .home-section__header h1 does not shrink with screen size e.g mobiles

### ISSUE THREAD

**Issue by TomOndiba** [website-templates/personal-portfolio_one-page-template#1]
Hi, Thanks for nice job on all your themes. I created a plugin for Elgg social network. However, I realized that the  .home-section__header h1 does not resize has the screen shrinks. Here is the link for the plugin https://elgg.org/plugins/2685613

HOW TO FIX THE ISSUE: I added this css code in the css/custom.min.css file

`/* Fixing h1 font size for Viewport screens */
h1 {
  font-size: 36px; /* Some tweener fallback that doesn't look awful */ 
  font-size: 12vw;
}`

**Comment by orlovmax** [comment]
@TomOndiba Hi, thanks for pointing that moment, mate. I adjusted headings size for mobiles.

However trick with `font-size:12vw` won't solve the issue. 12vw will make letters very huge on some screen sizes ( > 1440px); eg, on the 1920px screens font-size will be ~230px.
![screen shot 2017-08-26 at 14 31 07](https://user-images.githubusercontent.com/5341339/29741304-792b719a-8a72-11e7-87b9-135cc428b729.jpg)

I suggest you to use some js solution, like FitText.js to achieve flexible font-size. http://fittextjs.com
