### ISSUE TITLE
Icon links not working

### ISSUE THREAD

**Issue by BenQuigley** [website-templates/personal-portfolio_one-page-template#2]
The `a.icon` links on the in the `.contact-info` tile aren't working. I'll send a pull request if I can figure it out.

**Comment by BenQuigley** [comment]
Figured it out - it is that they're external links that say `rel` rather than `href`.

**Comment by BenQuigley** [comment]
So I guess this was my usage issue. Thanks!

**Comment by orlovmax** [comment]
Yeah, seems like `href` attribute is missing there. Thanks for pointing that, I'll add it.
And `rel="nofollow"` is just a SEO thing, and can be easily removed.

PS. Feel free to replace `index.html` page with `home html`, so current home will become the first page of your website.
