### ISSUE TITLE
adding topic #portfolio-websites

### ISSUE THREAD

**Issue by umihico** [website-templates/personal-portfolio_one-page-template#3]
Hello! I'm collecting screenshots of everybody's portfolio here.
https://umihico.github.io/thumbnailed-portfolio-websites/
If you don't mind, I'd like you to add topic #portfolio-website. Then I can crawl your cool portfolio next time. Thank you!

**Comment by orlovmax** [comment]
Hi! Sorry for the late response, unfortunately I missed this notification :(

No problem, mate, I've added #portfolio-website topic to that template.
Your project is awesome 👍 , so I'm happy to share this template with others.
