### ISSUE TITLE
How to make the page reload with any changes?

### ISSUE THREAD

**Issue by mcollums** [website-templates/personal-portfolio_one-page-template#4]
Very new to gulp and BrowserSync! In the read me it's mentioned that there's an option to make Browser Sync live reload. How can I implement this?

I would like the page to refresh with my changes automatically.

**Comment by orlovmax** [comment]
Hi,
In the [Tasks](https://github.com/website-templates/portfolio_one-page-template#tasks) section of readme you can see an alias `gulp dev` - it runs several tasks including browsersync.  It works 'out of the box'.

1. Make sure that you have installed node, npm and and gulp globally.
2. Clone this repo and install all packages by running `npm install` in your terminal from the root of the project. 
3. Run `gulp dev`  - it will start watching for changes and will open index.html in a browser on `http://localhost:3000`
4. Change anything in `dev` folder (config, sass styles, pug templates or js) and it will immediately refresh the page with your changes.

Use `Ctrl + C` to terminate watching and browsersync tasks.

Please note that all stuff from `build` folder is not watched by gulp, so changing them directly won't refresh the page in browser

**Comment by mcollums** [comment]
Ah, thank you! I don't think I understood what each task was doing.

**Comment by mcollums** [comment]
How can I deploy my finished template to github?

**Comment by orlovmax** [comment]
Seems like you're already deployed it, and it was mounted there https://mcollums.github.io/portfolio/build/

If you want to deploy this template here https://mcollums.github.io/portfolio - just push all stuff from a `build` folder to `gh-pages` branch (like [in this repo](https://github.com/website-templates/portfolio_one-page-template))

And if you want to deploy it to your account's page on this url https://mcollums.github.io/ ([like there](https://github.com/website-templates/website-templates.github.io)), then you need to create a `mcollums.github.io` repository and push all things from your build folder  to `master` branch

**Comment by JDScharf** [comment]
Hi Orlovmax,
I am having a similar issue and can't figure out how to deploy my template also.  I have not gotten as far in modifying it as mcollums, but any advice is super appreciated. 
https://github.com/JDScharf/Portfolio2 

Thank you,

Jason

**Comment by orlovmax** [comment]
@JDScharf 
Hi Jason,
I assume that you want to deploy your template here `http://jdscharf.github.io/Portfolio2/`
If so then just create a new `gh-pages` branch and push there compiled stuff from `build` folder

Here is an official guide, that explains how github pages work and how to deploy something to github https://pages.github.com/

This could be achieved in a few ways:

**1. The most simple and fast - using copy / paste**
- manually create a new folder
- init there empty repository
- link  remote repo
- create new `gh-pages` branch
- copy template files from your existing `build` folder and paste them to the folder you just created
- commit changes and push it to remote gh-pages branch

Something like this was described in a starter guide

**2. More complex - using nested repository to split `dev` and `build` folders between branches**
- create `gh-pages` branch
- clone it into `build` folder
- rebuild project
- commit changes and push it to gh-pages branch

At the end you'll get `dev` and `build` folders in `master` branch and `build` folder in `gh-pages` branch
_Note: If you don't want to have a `build` folder in master - then before creating nested repository just remove it and then exclude it using .gitignore_

Here is a detailed tutorial https://www.aymerick.com/2014/07/22/jekyll-github-pages-bower-bootstrap.html 

All demos on website-templates were built in that way

**3. Git submodules - a little bit tricky but seems like the most correct way to handle such case**
I didn't try to use it on github pages. But I'm sure that should work like a charm.

**Comment by JDScharf** [comment]
Hi Maxim,
Thank you so much for the information. I love the template you made and
will check these links out when I work on this more tonight :)

-Jason

**Comment by orlovmax** [comment]
@JDScharf You're welcome :)
